version: "3"

services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        restart: unless-stopped
        env_file: .env
        environment:
            - HOST=$HOST
            - SECRET=$SECRET
            - SITE_COOKIE=$SITE_COOKIE
            - CHAT_PORT=$CHAT_PORT
            - STORAGE_PORT=$STORAGE_PORT
            - DB_NAME=$DB_NAME
            - MONGO_HOST=$MONGO_HOST
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
        ports:
            - "80:8080"
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        networks:
            - app-network
    db:
        image: bionic
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        volumes:
            - dbdata:/data/db
        networks:
            - app-network
        entrypoint: ["setup-mongo.sh"]

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
    node_modules:
