version: "3"

services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        restart: unless-stopped
        env_file: .env
        environment:
            - HOST=$HOST
            - SECRET=$SECRET
            - SITE_COOKIE=$SITE_COOKIE
            - CHAT_PORT=$CHAT_PORT
            - STORAGE_PORT=$STORAGE_PORT
            - DB_NAME=$DB_NAME
            - MONGO_HOST=$MONGO_HOST
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
        ports:
            - "80:3000"
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        networks:
            - app-network
        depends_on:
            db:
                condition: service_healthy
    db:
        build:
            context: .
            dockerfile: mongo.Dockerfile
        image: mongo:4.4.4-bionic
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
            - MONGO_INITDB_DATABASE=$DB_NAME
        ports:
            - "27017:27017"
        volumes:
            - dbdata:/data/db
        networks:
            - app-network
        command: "--bind_ip_all --replSet rs0 --keyFile /data/mongod-keyfile --auth"
        healthcheck:
            test: test $$(echo "rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
            interval: 10s
            start_period: 30s
    mongo-client:
        image: mongo:4.4.4-bionic
        container_name: mongo-initializer
        restart: on-failure
        depends_on:
            db:
                condition: service_started
        volumes:
            - ./deployment-scripts:/deployment-scripts
        env_file: .env
        entrypoint:
            - /deployment-scripts/docker-initialize-mongo.sh
        command: "$MONGO_USERNAME $MONGO_PASSWORD $DB_NAME"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
    node_modules:
